### ISSUE TITLE
Best comedian

### ISSUE THREAD

**Issue by tutorialCreator** [tutorialCreator/Tutorial#10]
Suche mindestens einen Film, der die Kriterien ''Best comedian'' erfüllt, und füge ein passendes Bild anhand einer URL und den Titel in die MovieDB ein.

**Comment by AlexDidora** [comment]
Zach Galifianakis
Masterminds
https://images-na.ssl-images-amazon.com/images/M/MV5BMTQwNzI3NjIwMV5BMl5BanBnXkFtZTcwMzA1OTIwMw@@._V1_UY317_CR1,0,214,317_AL_.jpg
